#! /usr/bin/python3
import numpy
numbers = [101,201,301,401,501,601,701,801,901]
def f1():
    a = 1/3
    b = 1/5
    c = 1/7
    d = 1/9
    e = 1/11
    k = 201
    f = (-1)**(k+1)
    g = (2*k)-1
    h = ...
    m = 4*(1-a+b-c+d-e+0+(f/g))
    print(m)
    print(h)
f1()
